version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: wgt
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: wgt
    restart: always
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  wgt_backend:
    container_name: wgt_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:9999'
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://wgt:postgres_password@db/wgt
      SENTRY_DSN: Settings > Project > Client Keys (DSN) > Copy URL
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
networks: 
  net:
    driver: bridge