version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: wgt
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: wgt
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  wgt_backend:
    container_name: wgt_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:9999'
    restart: unless-stopped
    environment:
      # Backend Database URL (Postgres)
      DATABASE_URL: postgres://wgt:postgres_password@db/wgt
      # Sentry Backend DSN (Settings > Project > Client Keys (DSN) > Copy URL)
      SENTRY_DSN: Settings > Project > Client Keys (DSN) > Copy URL
      # API URL, (Ex. https://yourdomain.com/api)
      VUE_APP_ROOT_API: http://localhost:80/api
      # Sentry Frontend DSN (Settings > Project > Client Keys (DSN) > Copy URL)
      VUE_APP_SENTRY_DSN: Settings > Project > Client Keys (DSN) > Copy URL
      # Location of WGT Installation (Ex. Library)
      VUE_APP_WGT_LOCATION: Library
    depends_on:
      - db