version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: downloader
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: downloader
    restart: always
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  wgt_backend:
    container_name: wgt_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9999:80'
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://downloader:postgres_password@db/downloader
      SENTRY_DSN: https://305a3fee962f4a5397019e209c924a3b@o1031901.ingest.sentry.io/6177567
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
networks: 
  net:
    driver: bridge